### ISSUE TITLE
vagrant destroy on server, deletes portable storage volume?

### ISSUE THREAD

**Issue by fdask** [audiolize/vagrant-softlayer#67]
Just had a weird instance where doing a vagrant destroy on a softlayer virtual server instance created through vagrant, and this plugin, nuked a portable storage volume we had attached to the machine.

Wondering if that is known behaviour?   What mechanism does this code use to actually terminate a box?  Perhaps me checking the softlayer specific documentation can clarify the expected behaviour for me...

**Comment by ju2wheels** [comment]
We use the [Virtual_Guest#deleteObject](http://sldn.softlayer.com/reference/services/SoftLayer_Virtual_Guest/deleteObject) service method via the SoftLayer Ruby API. Cant speak to the behavior, I havent used this plugin, or SoftLayer in a few years.

**Comment by ju2wheels** [comment]
@fdask marking this as closed for now, if you have any follow up let us know. I think that its best to open your questions on behavior upstream at [softlayer-ruby](https://github.com/softlayer/softlayer-ruby) as there would be no fix here we could provide through this plugin since we only handle the instance lifecycle and not attached storage (delete behavior would be controlled via upstream API).
